spring:
#  datasource:
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: coooldh
#    password: coooldh1!
  datasource:
    master:
      type: org.apache.tomcat.jdbc.pool.DataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: coooldh
      password: coooldh1!
      maxIdle: 300
      initialSize: 10
      maxWait: 30000
      testOnBorrow: true
      validationQuery: SELECT 1
    slave:
      type: org.apache.tomcat.jdbc.pool.DataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test2?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
  #    url: jdbc:mysql://moca-ap-northeast-2a.cuxtg5bg36lw.ap-northeast-2.rds.amazonaws.com:3306/mocadb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: coooldh
      password: coooldh1!
      maxIdle: 300
      initialSize: 10
      maxWait: 30000
      testOnBorrow: true
      validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: mysql
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.type: trace
logging:
  level:
    ROOT: INFO
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
#    database-platform: com.vlending.cms.hibernate.CustomMySQLDialect
server:
  port: 5000
  connection-timeout: 20000
  error:
    whitelabel:
      enabled: false